// <auto-generated />
namespace ApiSolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createPostandCommenttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createPostandCommenttable));
        
        string IMigrationMetadata.Id
        {
            get { return "202011271018087_create Post and Comment table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
